### ISSUE TITLE
AddRel() should be declared where struct Link is (package namespace 'models')

### ISSUE THREAD

**Issue by danielweck** [readium/r2-streamer-go#26]
https://github.com/readium/r2-streamer-go/blob/master/models/metadata.go#L126
```go
func (link *Link) AddRel(rel string) {
	...
}
```

...should be moved to:
https://github.com/readium/r2-streamer-go/blob/master/models/publication.go#L38
```go
type Link struct {
        ...
}
```

**Comment by banux** [comment]
Is it was forget when we split the file i think.
