### ISSUE TITLE
No support for alt-rep/alt-script

### ISSUE THREAD

**Issue by HadrienGardeur** [readium/r2-streamer-go#5]
The current model does not support alt-rep/alt-script to provide a representation of a title or a contributor in another language/script.

This is mostly tied to the fact that we're directly de-serializing the structure to JSON: 
https://github.com/Feedbooks/webpub-streamer/blob/master/models/metadata.go#L6
https://github.com/Feedbooks/webpub-streamer/blob/master/models/metadata.go#L44

The Web Publication Manifest has extensive support for alternative representations of a string, more so than EPUB 3.1:
```json
"title": {
  "fr": "Vingt mille lieues sous les mers",
  "en": "Twenty Thousand Leagues Under the Sea",
  "ja": "海底二万里"
}
```

```json
"author": {
  "name": {
    "ru": "Михаил Афанасьевич Булгаков",
    "en": "Mikhail Bulgakov",
    "fr": "Mikhaïl Boulgakov"
  }
}
```

This is one area where streamers in other languages SHOULD NOT copy the current Go project and make sure that their model support the full extent of what the Web Publication Manifest can do.

Is there an easy way to deal with the serialization issue in Go without making everything else far more complex? cc @jpbougie @banux

**Comment by banux** [comment]
We can use advanced serialization describe in this article https://blog.gopheracademy.com/advent-2016/advanced-encoding-decoding/ we could  overrride the Contributor MarshalJSON() function.

We could store the data in another fields with an array for multi language contributor and use it to store the no principal languages.

**Comment by banux** [comment]
Merged we need to check if there other fields that contributor name and title.
